name: canil_management_app
description: "Aplicativo de gerenciamento de canil."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ãcones padrÃ£o do iOS (Apple)
  cupertino_icons: ^1.0.6

  # Gerenciamento de estado
  provider: ^6.1.2

  # ManipulaÃ§Ã£o de imagens
  image_picker: ^1.1.2

  # ComunicaÃ§Ã£o HTTP
  http: ^1.3.0

  # Armazenamento de preferÃªncias no dispositivo
  shared_preferences: ^2.3.3

  # FormataÃ§Ã£o de datas e nÃºmeros
  intl: ^0.18.0

  # Gerador de UUIDs (Identificadores Ãºnicos)
  uuid: ^3.0.7

  # NotificaÃ§Ãµes locais
  flutter_local_notifications: ^16.3.3

  # Abrir URLs e aplicativos externos como WhatsApp
  url_launcher: ^6.1.14

  # ðŸ“Œ Adicionado para agendamentos com `flutter_local_notifications`
  timezone: ^0.9.2

  # Exibir mensagens rÃ¡pidas na tela (exemplo: "Cadastro realizado com sucesso!")
  fluttertoast: ^8.2.2

  # Personalizar Ã­cones do aplicativo
  flutter_launcher_icons: ^0.13.1

  # Banco de dados local (SQLite)
  sqflite: ^2.2.8+4

  # ManipulaÃ§Ã£o de caminhos de arquivos
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/banner.png
    - assets/fonts/Pacifico-Regular.ttf

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

